### ISSUE TITLE
writeTHERM component input workingDir_ doesn't work

### ISSUE THREAD

**Issue by benmo1** [mostaphaRoudsari/Honeybee#517]
Honeybee Version: 0.0.59
Windows: Windows 7. 
Grasshopper: Version August-27 2014
Rhino: Version 5 SR12 64-bit

The writeTHERM component has an input workingDir_ which doesn't seem to work.
Any string that I feed it makes the whole component turn red and shut down.

There error that is thrown is:

1. Solution exception:unsupported operand type(s) for +: 'NoneType' and 'str'

It says the input type hint is a ghdoc. From what I gather there is only one of these for every instance of grasshopper that is running, so it seems unlikely that this should be the correct input variable type.

Thanks so for looking into this.

**Comment by mostaphaRoudsari** [comment]
@benmo1 thank you for posting the issues. We will check soon and let you know the results.

**Comment by chriswmackey** [comment]
@benmo1 ,

I can't recreate your error.  The workingDir feature works fine for me:
![workdirworking](https://cloud.githubusercontent.com/assets/5567574/16472576/1cb0ad04-3e33-11e6-92ef-9b773030ac85.JPG)


Can you post a link to a file that has the error? I won't be able to help much if I can't get the error to happen on my machine.

-Chris

**Comment by benmo1** [comment]
Here you go

[workingdirexample.zip](https://github.com/mostaphaRoudsari/Honeybee/files/341473/workingdirexample.zip)

Ben

**Comment by chriswmackey** [comment]
@benmo1 ,
After updating your file, it is working for me.  My guess is that it had something to do with a bug I fixed in the last few months.  The updated working file is here:
https://www.dropbox.com/s/62t94omr3a9o48d/workingdirdemo.gh?dl=0
Use the "Honyebee_Update Honeybee" component to keep your GH components synced with the version here on the github.  This will allow you to benefit from the latest bug fixes and features.
-Chris

**Comment by benmo1** [comment]
Hi Chris, thanks so much for your help.

However, this new component writeTHERM VER 0.0.59 MAY_13_2016 doesn't work on my machine. It has an error saying I need a newer version (see end). However, when I use the update Honeybee_Update Honeybee component and redrag the Honeybee_Honeybee component onto the canvas it doesn't resolve the issue. The problem is that I already have the latest release verison 0.0.59. Presumably you are using a version of honey bee that hasn't been released yet (> 0.0.59) and there is some code in the component that requires that version to work?

I will continue to use the writeTHERM VER 0.0.59 JAN_26_2016 component in the meantime.

---------------------------- specific error

1. You need a newer version of Honeybee to use this compoent.Use updateHoneybee component to update userObjects.
If you have already updated userObjects drag Honeybee_Honeybee component into canvas and try again.

**Comment by benmo1** [comment]
In Addition

Running the Honeybee_Update Honeybee component replaced 

readTHERM VER 0.0.59 JAN_26_2016

with

readTHERM VER 0.0.59 FEB_03_2016

which also doesn't work.

---------------- Error

1. Solution exception:global name 'SIorIP_' is not defined

**Comment by chriswmackey** [comment]
@benmo1 ,
Are you able to run the file that I uploaded at the dropbox link?  That one has the components up-to-date.

If you are NOT able to run it, then there is a problem that is specific to your system or the directory that you are trying to write to.  If you are able to run it, then your issues are just because you are not syncing with the github correctly.  Search [GH Discussions like this](http://www.grasshopper3d.com/group/ladybug/forum/topics/what-does-it-mean-when-i-have-this-error-message?commentId=2985220%3AComment%3A1233796&groupId=2985220%3AGroup%3A658987) for full instructions.

-Chris

**Comment by benmo1** [comment]
@chriswmackey 

I was able to run the file you uploaded, I just checked, thanks very much. Before I tried using the update components and I think I made a mistake on one of the inputs simultaneously so I thought it didn't work. This has been fixed!

Ben

**Comment by benmo1** [comment]
Thank you so much!!!
